package org.eclipselabs.recommenders.bookmark.tree;

import java.util.ArrayList;

public class FlatTreeNode
{
	private FlatTreeNode parent;
	private ArrayList<FlatTreeNode> children;
	private Object value;

	private TreeNode refersTo;

	public FlatTreeNode(TreeNode node)
	{
		this.value = node.getValue();
		this.isBookmarkNode = node.isBookmarkNode();
		this.isAutoGenerated = node.isAutoGenerated();
		this.refersTo = node;

		this.children = new ArrayList<FlatTreeNode>();

	}

	public FlatTreeNode()
	{
		this.isBookmarkNode = false;
		this.isAutoGenerated = true;
		this.children = new ArrayList<FlatTreeNode>();
	}

	private boolean isBookmarkNode;

	/**
	 * Describes whether a node was created automatically for building up the
	 * hierarchy for another node or whether it was dropped by the user
	 */
	private boolean isAutoGenerated;

	public boolean hasParent()
	{
		return (parent != null);
	}

	public boolean isAutoGenerated()
	{
		return isAutoGenerated;
	}

	public boolean isBookmarkNode()
	{
		return isBookmarkNode;
	}

	public void setValue(Object value)
	{
		this.value = value;
	}

	public Object getValue()
	{
		return value;
	}

	public void addChild(FlatTreeNode child)
	{
		children.add(child);
		child.setParent(this);
	}

	public void removeChild(FlatTreeNode child)
	{
		children.remove(child);
		child.setParent(null);
	}

	public FlatTreeNode[] getChildren()
	{
		return children.toArray(new FlatTreeNode[children.size()]);
	}

	public boolean hasChildren()
	{
		return children.size() > 0;
	}

	public void setParent(FlatTreeNode parent)
	{
		this.parent = parent;
	}

	public FlatTreeNode getParent()
	{
		return parent;
	}

	public TreeNode getReferencingNode()
	{
		return refersTo;
	}
}
