package org.eclipselabs.recommenders.bookmark.tree;

import java.util.ArrayList;

public class TreeNode
	implements BMNode
{
	private BMNode parent;
	private ArrayList<BMNode> children;
	private Object value;

	private boolean isBookmarkNode;

	/**
	 * Describes whether a node was created automatically for building up the
	 * hierarchy for another node or whether it was dropped by the user
	 */
	private boolean isAutoGenerated;

	public TreeNode(Object value, boolean isBookmarkNode,
			boolean isAutoGenerated)
	{
		this.value = value;
		this.children = new ArrayList<BMNode>();
		this.isBookmarkNode = isBookmarkNode;
		this.isAutoGenerated = isAutoGenerated;
	}

	@Override
	public boolean hasParent()
	{
		return (parent != null);
	}

	@Override
	public boolean isAutoGenerated()
	{
		return isAutoGenerated;
	}

	@Override
	public boolean isBookmarkNode()
	{
		return isBookmarkNode;
	}

	@Override
	public void setValue(Object value)
	{
		this.value = value;
	}

	@Override
	public Object getValue()
	{
		return value;
	}

	@Override
	public void addChild(BMNode child)
	{
		children.add(child);
		child.setParent(this);
	}

	@Override
	public void removeChild(BMNode child)
	{
		children.remove(child);
		child.setParent(null);
	}

	@Override
	public BMNode[] getChildren()
	{
		return (BMNode[]) children.toArray(new BMNode[children.size()]);
	}

	@Override
	public boolean hasChildren()
	{
		return children.size() > 0;
	}

	@Override
	public void setParent(BMNode parent)
	{
		this.parent = parent;
	}

	@Override
	public BMNode getParent()
	{
		return parent;
	}

}
