package org.eclipselabs.recommenders.bookmark.tree;

import java.util.ArrayList;

public class TreeNode {
	private TreeNode parent;
	private ArrayList<TreeNode> children;
	private Object value;

	private boolean isBookmarkNode;

	/**
	 * Describes whether a node was created automatically for building up the
	 * hierarchy for another node or whether it was dropped by the user
	 */
	private boolean isAutoGenerated;


	public TreeNode(Object value, boolean isBookmarkNode,
			boolean isAutoGenerated) {
		this.value = value;
		this.children = new ArrayList<TreeNode>();
		this.isBookmarkNode = isBookmarkNode;
		this.isAutoGenerated = isAutoGenerated;
	}

	public boolean hasParent() {
		return (parent != null);
	}

	public boolean isAutoGenerated() {
		return isAutoGenerated;
	}

	public boolean isBookmarkNode() {
		return isBookmarkNode;
	}

	public void setValue(Object value) {
		this.value = value;
	}

	public Object getValue() {
		return value;
	}

	public void addChild(TreeNode child) {
		children.add(child);
		child.setParent(this);
	}

	public void removeChild(TreeNode child) {
		children.remove(child);
		child.setParent(null);
	}

	public TreeNode[] getChildren() {
		return (TreeNode[]) children.toArray(new TreeNode[children.size()]);
	}

	public boolean hasChildren() {
		return children.size() > 0;
	}

	public void setParent(TreeNode parent) {
		this.parent = parent;
	}

	public TreeNode getParent() {
		return parent;
	}

}
