package org.eclipselabs.recommenders.bookmark.view.flat;

import org.eclipselabs.recommenders.bookmark.tree.TreeNode;

public class FlattenedTreeNode
	extends TreeNode
{

	private TreeNode refersTo;

	public FlattenedTreeNode(TreeNode node)
	{
		super(node.getValue(), node.isBookmarkNode(), node.isAutoGenerated());
		this.refersTo = node;
	}

}
