package org.eclipselabs.recommenders.bookmark.tests;

import static org.junit.Assert.*;

import org.eclipselabs.recommenders.bookmark.tree.TreeNode;
import org.eclipselabs.recommenders.bookmark.tree.persistent.GsonConverter;
import org.eclipselabs.recommenders.bookmark.tree.persistent.deserialization.RestoredTree;
import org.eclipselabs.recommenders.bookmark.tree.persistent.deserialization.TreeDeserializer;
import org.eclipselabs.recommenders.bookmark.tree.persistent.deserialization.TreeDeserializerFacade;
import org.junit.Test;

public class TreeDeserializerTest
{

	@Test
	public void testDeserialization()
	{
		String serializedTree = "{\"isExpanded\":true,\"children\":[{\"isExpanded\":false,\"children\":[],\"value\":\"A\",\"isBookmarkNode\":false,\"isAutoGenerated\":false},{\"isExpanded\":false,\"children\":[],\"value\":\"B\",\"isBookmarkNode\":false,\"isAutoGenerated\":false}],\"value\":\"\",\"isBookmarkNode\":true,\"isAutoGenerated\":true}";

		RestoredTree restoredTree = TreeDeserializer.deSerializeTree(
				serializedTree, new GsonConverter());

		TreeNode root = restoredTree.getRoot();
		assertEquals(2, root.getChildren().length);
		assertFalse(root.getChildren()[0].isAutoGenerated());
		assertFalse(root.getChildren()[1].isAutoGenerated());
		assertEquals(1, restoredTree.getExpanded().length);

	}

	@Test
	public void testDeserializationFacade()
	{
		String serializedTree = "{\"isExpanded\":true,\"children\":[{\"isExpanded\":false,\"children\":[],\"value\":\"A\",\"isBookmarkNode\":false,\"isAutoGenerated\":false},{\"isExpanded\":false,\"children\":[],\"value\":\"B\",\"isBookmarkNode\":false,\"isAutoGenerated\":false}],\"value\":\"\",\"isBookmarkNode\":true,\"isAutoGenerated\":true}";
		RestoredTree restoredTree = TreeDeserializerFacade
				.deserialize(serializedTree);
		TreeNode root = restoredTree.getRoot();
		assertEquals(2, root.getChildren().length);
		assertFalse(root.getChildren()[0].isAutoGenerated());
		assertFalse(root.getChildren()[1].isAutoGenerated());
		assertEquals(1, restoredTree.getExpanded().length);
	}

}
