package org.eclipselabs.recommenders.bookmark.tree.persistent.deserialization;

import java.util.HashMap;

import org.eclipse.core.resources.IFile;
import org.eclipse.jdt.core.IJavaElement;
import org.eclipselabs.recommenders.bookmark.tree.TreeNode;
import org.eclipselabs.recommenders.bookmark.tree.persistent.ObjectConverter;
import org.eclipselabs.recommenders.bookmark.tree.persistent.serialization.SerializedTreeNode;
import org.eclipselabs.recommenders.bookmark.tree.util.TreeValueConverter;

public class TreeDeserializer {

	public static RestoredTree deSerializeTree(String serialized,
			ObjectConverter converter) {

		Object[] deserialized = converter.convertToObject(serialized);

		SerializedTreeNode rootNode = (SerializedTreeNode) deserialized[0];

		HashMap<Object, String> map = new HashMap<Object, String>();

		TreeNode restoredTree = deSerializeTreeValues(rootNode, map);

		RestoredTree rstTree = new RestoredTree(restoredTree, map.keySet()
				.toArray(new TreeNode[0]));

		return rstTree;
	}

	private static TreeNode deSerializeTreeValues(
			SerializedTreeNode treeRootNode, HashMap<Object, String> map) {

		TreeNode newRootNode = deSeralizeTreeValuesRecursive(treeRootNode, map);
		newRootNode.setValue("");

		return newRootNode;

	}

	private static TreeNode deSeralizeTreeValuesRecursive(
			SerializedTreeNode subTreeNode, HashMap<Object, String> map) {

		Object value = subTreeNode.getValue();
		boolean isBookmark = subTreeNode.isBookmarkNode();
		boolean isAutoGenerated = subTreeNode.isAutoGenerated();

		TreeNode newSubTreeNode = createNodeWithRecoveredValue((String) value,
				isBookmark, isAutoGenerated);

		if (subTreeNode.isExpanded())
			map.put(newSubTreeNode, "");

		for (SerializedTreeNode child : subTreeNode.getChildren()) {
			TreeNode newSubTreeChildNode = deSeralizeTreeValuesRecursive(child,
					map);
			if (newSubTreeChildNode != null)
				newSubTreeNode.addChild(newSubTreeChildNode);
		}

		return newSubTreeNode;
	}

	private static TreeNode createNodeWithRecoveredValue(String value,
			boolean isBookmark, boolean isAutoGenerated) {

		IJavaElement element = TreeValueConverter
				.attemptTransformationToIJavaElement(value);
		if (element != null)
			return new TreeNode(element, isBookmark, isAutoGenerated);

		IFile file = TreeValueConverter.attemptTransformationToIFile(value);
		if (file != null)
			return new TreeNode(file, isBookmark, isAutoGenerated);

		return new TreeNode(value, isBookmark, isAutoGenerated);
	}

}
